### PR TITLE
Add CI configuration for build and relevant package scripts

### PR DESCRIPTION
**Pull request by drtechie**
- Added CI template that generates `environment.ci.ts` as per variables configured.
- Added package scripts that generates build based on `--configuration=ci`.

### CODE REVIEW

**Comment by drtechie** [comment]
Relates to #66 

Marking this PR as [WIP] as there are open questions wrt build.

**Comment by drtechie** [comment]
As per discussion in the linked issue #66, following additional changes have been made:

1. Remove grunt
2. Added CI profile in mvn
3. Edited README with build instructions

**Review by devikasuresh20 — CHANGES_REQUESTED** [review]
Changes looks fine.
But requesting for one change: 'Currently we are using the name "hwc-facility-app" for hwc-ui war. Please use this name instead of "hwcui"'.

**Review by devikasuresh20 — COMMENTED** [review]
As discussed with Sweta, please confirm about the corresponding API change and testing of application login functionality.

**Comment by drtechie** [comment]
@devikasuresh20 changed the name of the artifact to hwc-app-facility.

Regarding the comment about API, only the build and packaging of the application have been changed.
Otherwise, let me know what and how to test.

**Comment by drtechie** [comment]
https://github.com/PSMRI/HWC-UI/tree/develop/.github/workflows

The GitHub workflows folder has at least 2 files that don't have yaml extension.
@devikasuresh20 are they needed?
If yes, will change to .yaml, else delete the files.

**Review by devikasuresh20 — APPROVED** [review]

**Comment by devikasuresh20** [comment]
> https://github.com/PSMRI/HWC-UI/tree/develop/.github/workflows
> 
> The GitHub workflows folder has at least 2 files that don't have yaml extension. @devikasuresh20 are they needed? If yes, will change to .yaml, else delete the files.

I think it's required. As per the commits @Vidyaaa24 added it.

**Comment by drtechie** [comment]
@devikasuresh20 
https://github.com/PSMRI/HWC-UI/actions
GitHub Actions is not reading those files because it doesn't have a valid format.

**Comment by Vidyaaa24** [comment]
> > https://github.com/PSMRI/HWC-UI/tree/develop/.github/workflows
> > The GitHub workflows folder has at least 2 files that don't have yaml extension. @devikasuresh20 are they needed? If yes, will change to .yaml, else delete the files.
> 
> I think it's required. As per the commits @Vidyaaa24 added it.

all github actions files should have .yml extension I think it is missed

**Pull request merged**
