### PR TITLE
cleanup package.json

### PR DESCRIPTION
**Pull request by Vidyaaa24**

### CODE REVIEW

**Comment by drtechie** [comment]
This change should ideally have the lock file committed too.
Let's remove `package-lock.json` from .gitignore and commit it too.

**Comment by Vidyaaa24** [comment]
> This change should ideally have the lock file committed too. Let's remove `package-lock.json` from .gitignore and commit it too.

changes made please review

**Comment by Vidyaaa24** [comment]
> > This change should ideally have the lock file committed too. Let's remove `package-lock.json` from .gitignore and commit it too.
> 
> changes made please review @drtechie

**Review by drtechie — APPROVED** [review]

**Comment by drtechie** [comment]
Closes #51

**Pull request merged**
